---
# Disable coverage analysis - we handle coverage locally and via Codecov
coverage:
  enabled: false

engines:
  bandit:
    exclude_paths:
      - "*/tests/**"
      - "*/test_*.py"
      - "**/test_settings.py"
      - "characters/tests/test_owned_locations.py"
    rules:
      B105:  # hardcoded_password_string
        exclude:
          - "*/tests/**"
          - "*/test_*.py"
          - "**/test_settings.py"
          - "characters/tests/test_owned_locations.py"
      B106:  # hardcoded_password_funcarg
        exclude:
          - "*/tests/**"
          - "*/test_*.py"
          - "**/test_settings.py"
          - "characters/tests/test_owned_locations.py"
      B107:  # hardcoded_password_default
        exclude:
          - "*/tests/**"
          - "*/test_*.py"
          - "**/test_settings.py"
          - "characters/tests/test_owned_locations.py"

  flake8:
    exclude_paths:
      - "migrations/"
      - "venv/"
      - "__pycache__/"

  pylint:
    exclude_paths:
      - "migrations/"
      - "venv/"
      - "__pycache__/"

exclude_paths:
  - "migrations/"
  - "venv/"
  - "__pycache__/"
  - "node_modules/"
  - "*.min.js"
  - "*.min.css"
