# Generated by Django 5.0.8 on 2025-08-23 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_initial"),
        ("characters", "0002_initial"),
        ("items", "0005_alter_item_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this object",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(help_text="Name of the object", max_length=100),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["campaign", "is_deleted"], name="items_campaign_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["created_by", "is_deleted"], name="items_creator_deleted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_deleted", "created_at"], name="items_deleted_created_idx"
            ),
        ),
    ]
